services:
  catalog-scanner:
    image: catalog-scanner:latest
    container_name: catalog-scanner
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /mnt/main/containers/custom-apps/catalog-scanner/tmp:/tmp
      - ./templates:/app/templates:ro
    environment:
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata
